# Generated by Django 5.1.4 on 2025-05-07 22:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('passaporte', 'Passaporte')], default='cpf', max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('suite_casal', 'Suíte Casal'), ('suite_duplo', 'Suíte Duplo ou Casal'), ('suite_quadruplo', 'Suíte Quádruplo')], default='suite_casal', max_length=20)),
                ('classe', models.CharField(choices=[('luxo_terreo', 'Luxo Térreo'), ('luxo_superior', 'Luxo Superior'), ('padrao', 'Padrão')], default='padrao', max_length=20)),
                ('capacidade_adultos', models.PositiveSmallIntegerField(default=2)),
                ('capacidade_criancas', models.PositiveSmallIntegerField(default=1)),
                ('capacidade_maxima', models.PositiveSmallIntegerField(default=2)),
                ('valor_diaria_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Manutenção'), ('bloqueado', 'Bloqueado')], default='disponivel', max_length=20)),
                ('tamanho', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tem_vista', models.BooleanField(default=False)),
                ('tipo_banheiro', models.CharField(choices=[('privativo', 'Banheiro Privativo'), ('compartilhado', 'Banheiro Compartilhado'), ('privativo_externo', 'Privativo fora do quarto')], default='privativo', max_length=30)),
                ('recursos_banheiro', models.CharField(choices=[('apenas_chuveiro', 'Apenas chuveiro'), ('chuveiro_banheira', 'Chuveiro e banheira'), ('apenas_banheira', 'Apenas banheira')], default='apenas_chuveiro', max_length=30)),
                ('espaco_externo', models.CharField(choices=[('varanda_coberta', 'Varanda coberta'), ('varanda_descoberta', 'Varanda sem cobertura'), ('patio', 'Pátio'), ('jardim', 'Jardim privativo'), ('nenhum', 'Nenhum')], default='nenhum', max_length=30)),
                ('amenities', models.JSONField(blank=True, default=dict, null=True)),
                ('camas', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chegada', models.DateField()),
                ('data_saida', models.DateField()),
                ('hora_chegada_prevista', models.TimeField(default='14:00')),
                ('hora_saida_prevista', models.TimeField(default='12:00')),
                ('num_adultos', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('num_criancas', models.PositiveSmallIntegerField(default=0)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('no_show', 'No Show')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_chegada', 'quarto'],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_consumo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Check-out',
                'verbose_name_plural': 'Check-outs',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
            },
        ),
    ]
