services:
  - type: web
    name: villacontainer
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: villacontainer-db
          property: connectionString

databases:
  - name: villacontainer-db
    databaseName: villacontainer
    user: villacontainer