# Generated by Django 5.1.4 on 2024-12-22 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarto', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('pago', 'Pago')], default='aberto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cardapio/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozinha.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemConsumacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('observacao', models.TextField(blank=True)),
                ('consumacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozinha.consumacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cozinha.itemcardapio')),
            ],
        ),
        migrations.AddField(
            model_name='consumacao',
            name='itens',
            field=models.ManyToManyField(through='cozinha.ItemConsumacao', to='cozinha.itemcardapio'),
        ),
    ]
