# Generated by Django 5.1.4 on 2025-03-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarto', models.CharField(max_length=50)),
                ('nome_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('pago', 'Pago')], default='aberto', max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário'), ('hospede', 'Hóspede')], default='cliente', max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('outros', 'Outros')], max_length=50, null=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The public id of the uploaded file', max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(help_text='The original name of the uploaded image', max_length=100)),
                ('width', models.IntegerField(help_text='Width in pixels')),
                ('height', models.IntegerField(help_text='Height in pixels')),
                ('format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='cozinha.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria_pai__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.URLField(blank=True, max_length=500, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cozinha.categoria')),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
                'ordering': ['categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemConsumacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('observacao', models.TextField(blank=True)),
                ('consumacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozinha.consumacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cozinha.itemcardapio')),
            ],
        ),
        migrations.AddField(
            model_name='consumacao',
            name='itens',
            field=models.ManyToManyField(through='cozinha.ItemConsumacao', to='cozinha.itemcardapio'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('outros', 'Outros')], default='dinheiro', max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('consumacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='cozinha.consumacao')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
