# Generated by Django 5.1.4 on 2025-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='items/'),
        ),
    ]
