# Generated by Django 5.1.4 on 2024-12-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0002_categoria_categoria_pai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['categoria_pai__nome', 'nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='itemcardapio',
            options={'ordering': ['categoria__nome', 'nome'], 'verbose_name': 'Item do Cardápio', 'verbose_name_plural': 'Itens do Cardápio'},
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cozinha.categoria'),
        ),
    ]
