# Generated by Django 5.1.4 on 2024-12-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0003_alter_categoria_options_alter_itemcardapio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
