# Generated by Django 5.1.4 on 2025-04-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0004_adiciona_campo_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='preco_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='venda',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
