# Generated by Django 5.1.4 on 2024-12-27 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0004_itemcardapio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumacao',
            name='isBusinessWorker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='preco_funcionario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('consumacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='cozinha.consumacao')),
            ],
        ),
    ]
