# Generated by Django 5.1.4 on 2024-12-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0005_consumacao_isbusinessworker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('outros', 'Outros')], default='dinheiro', max_length=50),
        ),
    ]
