# Generated by Django 5.1.4 on 2024-12-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0006_alter_pagamento_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcardapio',
            old_name='preco_funcionario',
            new_name='preco_custo',
        ),
    ]
