# Generated by Django 5.1.4 on 2024-12-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0007_rename_preco_funcionario_itemcardapio_preco_custo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumacao',
            options={'ordering': ['-data_hora']},
        ),
        migrations.RemoveField(
            model_name='consumacao',
            name='isBusinessWorker',
        ),
        migrations.AddField(
            model_name='consumacao',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumacao',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumacao',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='consumacao',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('outros', 'Outros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consumacao',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consumacao',
            name='tipo_cliente',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário'), ('hospede', 'Hóspede')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='consumacao',
            name='quarto',
            field=models.CharField(max_length=10),
        ),
    ]
