# Generated by Django 5.1.4 on 2025-01-04 20:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0008_alter_consumacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumacao',
            name='quarto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
