# Generated by Django 5.1.4 on 2025-01-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0009_alter_consumacao_quarto_alter_itemcardapio_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The public id of the uploaded file', max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(help_text='The original name of the uploaded image', max_length=100)),
                ('width', models.IntegerField(help_text='Width in pixels')),
                ('height', models.IntegerField(help_text='Height in pixels')),
                ('format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
