# Generated by Django 5.1.4 on 2026-04-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('Cozinha', 'Cozinha'), ('Limpeza', 'Limpeza'), ('Jardim', 'Jardim'), ('Manutenção', 'Manutenção'), ('Administrativo', 'Administrativo')], max_length=50)),
                ('turno_sugerido', models.CharField(choices=[('6-11h', '6-11h'), ('11-16h', '11-16h'), ('16-21h', '16-21h'), ('Flexível', 'Flexível')], max_length=20)),
                ('tempo_estimado', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dificuldade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Baixa', max_length=10)),
                ('frequencia', models.CharField(choices=[('Diária', 'Diária'), ('2x semana', '2x semana'), ('3x semana', '3x semana'), ('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal'), ('Conforme demanda', 'Conforme demanda')], default='Diária', max_length=20)),
                ('proc_type', models.CharField(choices=[('checklist', 'Checklist'), ('text', 'Texto livre')], default='checklist', max_length=10)),
                ('checklist_steps', models.JSONField(blank=True, default=list)),
                ('proc_text', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['area', 'nome'],
            },
        ),
    ]
