# Generated by Django 5.1.4 on 2026-04-04 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('habilidade', 'Habilidade'), ('conquista', 'Conquista')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Insígnia',
                'verbose_name_plural': 'Insígnias',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='volunteers/')),
                ('data_chegada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('pais_origem', models.CharField(blank=True, max_length=100)),
                ('idiomas', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('saiu', 'Saiu'), ('aguardando', 'Aguardando')], default='ativo', max_length=20)),
                ('habilidades', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'habilidade'}, related_name='volunteers', to='voluntarios.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turno', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluída')], default='pending', max_length=20)),
                ('horas_gastas', models.FloatField(blank=True, null=True)),
                ('checklist_progress', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='voluntarios.atividade')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='voluntarios.volunteer')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data', 'turno', 'template__nome'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manutenção', 'Manutenção'), ('comportamento', 'Comportamento'), ('saúde', 'Saúde'), ('segurança', 'Segurança'), ('outros', 'Outros')], max_length=50)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('média', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=20)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences_criadas', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='voluntarios.volunteer')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data', 'prioridade'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('folga', 'Folga')], max_length=20)),
                ('data', models.DateField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='voluntarios.volunteer')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['data', 'volunteer'],
                'unique_together': {('volunteer', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntarios.badge')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_concedidos', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='voluntarios.volunteer')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'unique_together': {('volunteer', 'badge')},
            },
        ),
    ]
