# Generated by Django 5.1.4 on 2026-04-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_badge_volunteer_task_occurrence_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='perguntas_finalizacao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/fotos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='problema_reportado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='respostas_finalizacao',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='turno',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
