# Generated by Django 5.1.4 on 2026-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_atividade_perguntas_finalizacao_task_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='turno',
            field=models.CharField(choices=[('6-11h', '6-11h'), ('11-16h', '11-16h'), ('16-21h', '16-21h'), ('folga', 'Folga'), ('Flexível', 'Flexível')], max_length=20),
        ),
    ]
